---
title: "Tidymodels for bird baths in Australia"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Source: https://juliasilge.com/blog/bird-baths/

```{r}
library(tidyverse)
library(tidymodels)

bird_baths <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-31/bird_baths.csv")

bird_baths |> 
  count(urban_rural)
bird_baths
```


```{r}
top_birds <- 
  bird_baths |> 
  # select for rows with NA in urban_rural
  filter(is.na(urban_rural)) |> 
  # arrange in decreasing order of bird_count
  arrange(-bird_count) |> 
  # take the top 15 rows in the bird_count column
  slice_max(bird_count, n = 15) |> 
  # returns a character vector of the values in bird_type column
  pull(bird_type)
```

```{r}
bird_parsed <- bird_baths |> 
  filter(!is.na(urban_rural), bird_type %in% top_birds) |> 
  group_by(urban_rural, bird_type) |> 
  summarize(bird_count = mean(bird_count), .groups = "drop")

p1 <- bird_parsed |> 
  ggplot(aes(x = bird_count, y = fct_reorder(bird_type, bird_count))) +
  geom_segment(data = bird_parsed |> 
                 pivot_wider(names_from = urban_rural, 
                             values_from = bird_count),
               aes(x = Rural, xend = Urban, y = bird_type, yend = bird_type),
               alpha = 0.7, color = "grey70", size = 1.5) +  
  geom_point(aes(color = urban_rural), size = 3) +
  scale_x_continuous(labels = scales::percent) +
  labs(x = "Probability of seeing a bird", y = NULL, color = NULL)
```

```{r}
bird_df <- 
  bird_baths |> 
  filter(!is.na(urban_rural), bird_type %in% top_birds) |> 
  mutate(bird_count = if_else(bird_count > 0, "bird", "no bird")) |> 
  mutate_if(is.character, as.factor)
```

```{r}
# split data into testing and training
set.seed(123)
bird_split <- initial_split(bird_df, strata = bird_count)
bird_train <- training(bird_split)
bird_test <- testing(bird_split)

# split the data into V groups/folds 
set.seed(234)
bird_folds <- vfold_cv(bird_train, strata = bird_count)
```

```{r}
glm_spec <- logistic_reg()

rec_basic <- recipe(bird_count ~ urban_rural + bird_type, data = bird_train) |> 
  step_dummy(all_nominal_predictors())

wf_basic <- workflow(rec_basic, glm_spec)
```

```{r}
# fit 10 times to 10 resampling folds
doParallel::registerDoParallel()
ctrl_preds <- control_resamples(save_pred = TRUE)
rs_basic <- fit_resamples(wf_basic, bird_folds, control = ctrl_preds)

collect_metrics(rs_basic)
```

```{r}
augment(rs_basic) |> 
  roc_curve(bird_count, .pred_bird) |> 
  autoplot()
```

```{r}
# add interactions
rec_interact <- 
  rec_basic |> 
  step_interact(~ starts_with("urban_rural"):starts_with("bird_type"))

wf_interact <- workflow(rec_interact, glm_spec)
rs_interact <- fit_resamples(wf_interact, bird_folds, control = ctrl_preds)
```

```{r}
collect_metrics(rs_interact)
augment(rs_interact) |> 
  roc_curve(bird_count, .pred_bird) |> 
  autoplot()
```

```{r}
# fit the model once to the entire training dataset
bird_fit <- fit(wf_interact, bird_train)

# apply the trained model to new data
predict(bird_fit, bird_test, type = "prob")
```

```{r}
new_bird_data <- tibble(bird_type = top_birds) |> 
  crossing(urban_rural = c("Urban", "Rural"))

new_bird_data
```

```{r}
bird_preds <- 
  augment(bird_fit, new_bird_data) |> 
  bind_cols(
    predict(bird_fit, new_bird_data, type = "conf_int")
  )

names(bird_preds)
```

```{r}
p2 <- bird_preds |> 
  ggplot(aes(x = .pred_bird, y = bird_type, color = urban_rural)) +
  geom_point(size = 3) +
  geom_errorbar(aes(xmin = .pred_lower_bird,
                    xmax = .pred_upper_bird),
                width = 0.2, size = 1.2, alpha = 0.7) +
  scale_x_continuous(labels = scales::percent) +
  labs(x = "Predicted probability of seeing a bird", 
       y = NULL, 
       color = NULL)

library(patchwork)
p1 + p2
```

